### ISSUE TITLE
네이버 소셜로그인 오류

### ISSUE THREAD

**Issue by parkmuhyeun** [woowacourse-teams/2023-celuveat#249]
## 🐞 무슨 버그인가요?

네이버 로그인을 하면 다음과 같이 뜹니다!

![image](https://github.com/woowacourse-teams/2023-celuveat/assets/76938931/7780c3c4-733e-45c8-81ab-1c6bbf112623)

**Comment by wonyongChoi05** [comment]
저는 아예 안뜨네요...

<img width="1728" alt="스크린샷 2023-08-07 13 55 24" src="https://github.com/woowacourse-teams/2023-celuveat/assets/94087228/924e5265-2407-42ae-9db8-6d30b710e0b5">

**Comment by iamjooon2** [comment]
로그인이 다 새로고침 해야 뜨더라구요
