### ISSUE TITLE
[🐞 bug] 지도 문제

### ISSUE THREAD

**Issue by jjongwa** [woowacourse-teams/2023-celuveat#258]
## 🐞 무슨 버그인가요?
```
사진 첨부
```

<br><br>

## 🧐 재현하는 법
1. 줌아웃을 쭉 하면 보입니다.

<br><br>

## 😎 예상 동작
```
동해가 나와야 할텐데..
이건 논란이 있겠는걸 ...
```

<br><br>

## 🌄 관련 사진
<img width="356" alt="image" src="https://github.com/woowacourse-teams/2023-celuveat/assets/77482065/06234d21-ef1b-4334-9d5b-e265e49f051c">

<br><br>

## 🦋 추가적인 내용
```
근데 이거 저희도 똑같음..ㅋ쿠ㅜ
```

<br><br>

**Comment by LJW25** [comment]
디노 우리도 떳떳하지 못한데 여기서 이러시면 곤란합니다..
