### ISSUE TITLE
[🐞 bug] 하트 클릭하면 네이버 지도로 이동

### ISSUE THREAD

**Issue by ashleysyheo** [woowacourse-teams/2023-celuveat#261]
## 🐞 무슨 버그인가요?
```
난 하트 클릭했는데, 갑자기 네이버 지도로 이동
```

<br><br>

## 🧐 재현하는 법
1. 

<br><br>

## 😎 예상 동작
```

```

<br><br>

## 🌄 관련 사진
<img width="362" alt="Screenshot 2023-08-07 at 1 56 46 PM" src="https://github.com/woowacourse-teams/2023-celuveat/assets/51967731/f72a05a1-db69-4a6a-b7ab-90a8e935b45c">

<br><br>

## 🦋 추가적인 내용
```

```

<br><br>

**Comment by wonyongChoi05** [comment]
<img width="346" alt="스크린샷 2023-08-07 13 59 27" src="https://github.com/woowacourse-teams/2023-celuveat/assets/94087228/cedc7e0d-26f5-4fb4-b4f1-9b40737fe530">

혹시 이것도..??!
