### ISSUE TITLE
[feat] Header와 프로필 이미지를 만드는 컴포넌트 구현

### ISSUE THREAD

**Issue by D0Dam** [woowacourse-teams/2023-celuveat#28]
### Header
<img width="1049" alt="스크린샷 2023-07-07 오전 11 29 23" src="https://github.com/woowacourse-teams/2023-celuveat/assets/51052049/72be7bf2-8242-44da-85e5-11a1399d4d29">

### ProfileImage
<img width="193" alt="스크린샷 2023-07-05 오후 5 57 17" src="https://github.com/woowacourse-teams/2023-celuveat/assets/51052049/3f530a0b-54af-49b6-b751-57d8169d4cd5">

### Todo
- [ ] Header를 구현한다.
- [ ] 프로필 이미지를 만드는 컴포넌트를 구현한다.

**Comment by TaeyeonRoyce** [comment]
Issue 네이밍 컨벤션 지켜주세요!
`~ 구현한다` -> `~ 구현`
