### ISSUE TITLE
[fix] Webpack 환경설정 속성 오타 오류 해결

### ISSUE THREAD

**Issue by turtle601** [woowacourse-teams/2023-celuveat#55]
## Error
- Webpack의 resolve 속성 중 extendsion 배열 값 중 오타가 있었습니다.. 

<img width="456" alt="스크린샷 2023-07-10 오후 12 00 44" src="https://github.com/woowacourse-teams/2023-celuveat/assets/78203399/792483b7-1a8f-4ae3-899e-67fa5549af87">

__초록색 값이 되도록 수정할께여~~__

**Comment by shackstack** [comment]
제목 `[Fix]` -> `[fix]`로 수정 부탁드려요~
