### ISSUE TITLE
프론트엔드 컨벤션 관련 논의

### ISSUE THREAD

**Issue by turtle601** [woowacourse-teams/2023-celuveat#81]
## storybook args 선언 방식

1. args를 변수로 선언
2. 스토리북 args에 하드코딩하는 식

## api 타입 선언

@types에 api 타입을 선언하고 해당 타입을 재사용하자. 

- 재사용할지 말지
- 타입파일 선언 방식(ex. celebs.types.ts)

**Comment by D0Dam** [comment]
오프라인으로 같이 이야기하고 정해보아요!

**Comment by D0Dam** [comment]
# 결론 

### storybook args 선언 방식
- 기존대로 스토리북 args에 props를 작성

### api 타입 선언
- 우선 재사용 없이 작성, 이후 Celeb 등의 공통 분모를 가지는 찾아내 재활용 할 타입으로 선언 후 리팩토링
